---
- name: Set up an Apache Webserver
  hosts: Web
  become: yes
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: absent

  - name: Ensure httpd is running or not
    service:
      name: httpd 
      state: started

  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted